spring:
  application:
    name: prometheus-study

server:
  port: 8080

management:
  metrics:
    export:
      simple:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  endpoint:
    shutdown:
      enabled: true

